export const INSTITUTE = {
  name: "Nightingale Nursing & Midwifery Institute",
  nameBn: "নাইটিঙ্গেল নার্সিং এন্ড মিডওয়াইফারি ইনস্টিটিউট",
  phone: "01727-127356",
  phoneTel: "+8801727127356",
  whatsapp: "8801727127356",
  email: "nightingalennmi2020@gmail.com",
  website: "www.nightingalennmi.com",
  address: "৩৭/৬/১, রোড নং-৬, আদাবর, মোহাম্মদপুর, ঢাকা - ১২০৭",
  addressEn: "Adabor / Mohammadpur, Dhaka, Bangladesh",
};

export const NAV_LINKS = [
  { href: "#home", bn: "হোম", en: "Home" },
  { href: "#about", bn: "আমাদের সম্পর্কে", en: "About Us" },
  { href: "#courses", bn: "কোর্স", en: "Courses" },
  { href: "#services", bn: "সেবা", en: "Services" },
  { href: "#japan", bn: "জাপান ক্যারিয়ার", en: "Japan Career" },
  { href: "#gallery", bn: "গ্যালারি", en: "Gallery" },
  { href: "#contact", bn: "যোগাযোগ", en: "Contact" },
];

export const COURSES = [
  {
    icon: "🩺",
    tag: "Diploma",
    title: "Diploma in Nursing",
    titleBn: "ডিপ্লোমা ইন নার্সিং",
    desc: "নার্সিংয়ের মৌলিক জ্ঞান, patient care, clinical practice ও professional skills-এর জন্য প্রশিক্ষণ।",
    level: "৩ বছর মেয়াদি",
  },
  {
    icon: "👩‍⚕️",
    tag: "Diploma",
    title: "Diploma in Midwifery",
    titleBn: "ডিপ্লোমা ইন মিডওয়াইফারি",
    desc: "মিডওয়াইফারি ও maternal-care focused learning, practical skill এবং career preparation।",
    level: "৩ বছর মেয়াদি",
  },
  {
    icon: "🤝",
    tag: "Caregiving",
    title: "Level-2 General Caregiving",
    titleBn: "জেনারেল কেয়ারগিভিং",
    desc: "কেয়ারগিভিংয়ের মৌলিক দক্ষতা—daily care, communication ও safety practice।",
    level: "Level 2",
  },
  {
    icon: "🏥",
    tag: "Health Care",
    title: "Level-2 Primary Health Care",
    titleBn: "প্রাইমারি হেলথ কেয়ার সার্ভিস",
    desc: "প্রাথমিক স্বাস্থ্যসেবা, স্বাস্থ্যসচেতনতা ও রোগীর প্রাথমিক পরিচর্যার প্রশিক্ষণ।",
    level: "Level 2",
  },
  {
    icon: "👵",
    tag: "Level-3",
    title: "Caregiving for Elderly Persons",
    titleBn: "প্রবীণ পরিচর্যা",
    desc: "বয়স্কদের বেডসাইড কেয়ার, mobility support ও hygiene care-এর হাতে-কলমে প্রশিক্ষণ।",
    level: "Level 3",
  },
  {
    icon: "👶",
    tag: "Level-3",
    title: "Caregiving for Infant, Toddler & Children",
    titleBn: "শিশু পরিচর্যা",
    desc: "শিশু ও নবজাতকের যত্ন, পুষ্টি, নিরাপত্তা এবং বিকাশ-সহায়ক পরিচর্যা।",
    level: "Level 3",
  },
  {
    icon: "🧠",
    tag: "Level-3",
    title: "Dementia Caregiving",
    titleBn: "ডিমেনশিয়া কেয়ারগিভিং",
    desc: "স্মৃতিভ্রংশ রোগীর আচরণ বোঝা, ধৈর্যশীল যোগাযোগ ও নিরাপদ পরিচর্যা।",
    level: "Level 3",
  },
  {
    icon: "🧑‍🦽",
    tag: "Level-3",
    title: "Caregiving for Persons with Special Needs",
    titleBn: "বিশেষ চাহিদাসম্পন্ন ব্যক্তির পরিচর্যা",
    desc: "বিশেষ চাহিদাসম্পন্ন ব্যক্তিদের সহায়তা, therapy support ও দৈনন্দিন পরিচর্যা।",
    level: "Level 3",
  },
  {
    icon: "🇯🇵",
    tag: "Japanese",
    title: "Japanese Language N5 & N4",
    titleBn: "জাপানি ভাষা শিক্ষা",
    desc: "জাপানে কাজ/শিক্ষার প্রস্তুতির জন্য Japanese language foundation—N5 থেকে N4 pathway।",
    level: "N5 → N4",
  },
];

export const COURSE_OPTIONS = [
  "Diploma in Nursing",
  "Diploma in Midwifery",
  "General Caregiving",
  "Primary Health Care",
  "Elderly Caregiving",
  "Dementia Caregiving",
  "Children Caregiving",
  "Special Needs Caregiving",
  "Japanese N5",
  "Japanese N4",
  "Japan Caregiver Pathway",
];
